src/hir/hir_maker.rs
src/hir/index.rs
src/hir/mod.rs
src/main.rs
src/stdlib/mod.rs

The implementation is quite simple; just add corelib/*.sk before the user program.
Note that we need to merge methods because there may be two definitions of class Int, etc.

Support writing corelib with Shiika

---

src/code_gen/mod.rs
src/hir/hir_maker.rs
src/hir/index.rs
src/names.rs

This was failing
```
class A; end
puts A.name
```

fix: Ancestor initialize

---

src/ast.rs
src/code_gen/gen_exprs.rs
src/hir/convert_exprs.rs
src/hir/mod.rs
src/parser/expression_parser.rs
src/ty.rs

Parse Array literal

---

src/code_gen/boxing.rs
src/code_gen/gen_exprs.rs
src/code_gen/mod.rs
src/corelib/float.rs.erb
src/corelib/int.rs.erb

This change assumes
- 64bit env (i.e. pointers are 64bit)
- Address acquired by GC_malloc is 4 bytes aligned (i.e. ends with ~00)
refs #84

feat: Change Bool to i64_type

---

src/code_gen/gen_exprs.rs
src/hir/class_dict.rs
src/hir/convert_exprs.rs
src/hir/mod.rs
src/ty.rs

`[1,2]` is now inferred as `Array<Int>`, not `Array<Object>`.
refs #101

Infer more specific type of array

---

src/runner.rs

Since `Command#output()?` only checks whether the command process is run, but not check the process's status code.
I found this when the clang build is failed because I don't have libgc-dev installed on my machine, but the codes continues to try to run the build result but the result binary is not generated.

fix(runner): check clang status code

---

src/runner.rs

Currently `shiika run` is broken due to the run command tring to using `out_path` without `./` prefix, and this leads to let the OS tries to find the binary from PATH.

fix(runner): binary path to run

---

README.md

Seems current there were some unnecessary indents on the code block on README.md, this PR is fixing this. And I thought we can using the crystal's syntax highlight for now since their's grammar is similar now.
You can take a preview on the render result here: https://github.com/aisk/shiika/blob/ed798859ef3a7613619fd0c1b3c067c3ad6a7b6c/README.md

docs: update markdown format for readme

---

builtin/array.sk
builtin/lambda.sk
src/ast.rs
src/code_gen/gen_exprs.rs
src/code_gen/mod.rs
src/hir/class_dict/indexing.rs
src/hir/class_dict/query.rs
src/hir/convert_exprs.rs
src/hir/hir_maker.rs
src/hir/mod.rs
src/hir/signature.rs
src/hir/sk_class.rs
src/names.rs
src/parser/expression_parser.rs
src/ty.rs
tests/expression_parser_test.rs
tests/sk/array.sk

Evaluate `A<B>` to a specific class

---

src/code_gen/gen_exprs.rs
src/code_gen/lambda.rs
src/hir/convert_exprs.rs
src/hir/mod.rs
src/ty.rs
src/type_checking/mod.rs

- If the type of either branch is Void, put refenence of `::Void` to
the end of the exprs of the other branch so that both branch has
the same type (i.e. `Void`).
- If the type of either branch is Never (i.e. `break`), the value of
if-expr is the type of the other branch and do not use `phi` (or
broken .ll is generated.)
fix #184

fix: Proper handilng of Void/Never if-clause

---

src/parser/expression_parser.rs
src/parser/lexer.rs
src/parser/token.rs
tests/sk/string.sk

This PR implements `#{}` in a string literal and also `\{}`, which calls .inspect instead of .to_s.

String interpolation

---

README.md

The default hacking guide will leads to fail on macOS with homebrew.

Add compile instructions on README.md

---

doc/shg/src/hir.md
src/code_gen/gen_exprs.rs
src/hir/convert_exprs.rs
src/hir/hir_maker.rs
src/hir/hir_maker_context.rs
src/hir/mod.rs
src/hir/signature.rs

Current `HirMakerContext` has union of members which are needed in each situation. This PR split it into `ToplevelCtx` `ClassCtx` `MethodCtx` `LambdaCtx`.

Refactor HirMakerContext

---

builtin/_lambda.sk
src/ast.rs
src/code_gen/code_gen_context.rs
src/code_gen/gen_exprs.rs
src/code_gen/lambda.rs
src/code_gen/mod.rs
src/corelib/fn_x.rs
src/error.rs
src/hir/convert_exprs.rs
src/hir/hir_maker.rs
src/hir/hir_maker_context.rs
src/hir/mod.rs
src/names.rs
src/parser/expression_parser.rs
tests/sk/loops_and_conditionals.sk

- ~~[ ] hir: Set FnX#is_fn~~
- Invoke FnX#call
- After that, depending on FnX#exit_status:
- Do nothing if it has exited normally
- Jump to the end of current method if it has exited with `break`
fix #177

impl. break from block 

---

doc/guide/src/SUMMARY.md
doc/guide/src/expressions.md
doc/spec/src/expressions.md
src/code_gen/gen_exprs.rs
src/code_gen/lambda.rs
src/corelib/fn_x.rs
src/hir/convert_exprs.rs
src/hir/mod.rs
src/names.rs
src/parser/expression_parser.rs
src/ty.rs
tests/sk/block.sk
tests/sk/lambda.sk
tests/sk/loops_and_conditionals.sk

This PR adds `HirLambdaInvocation` and removes `FnX#call`.
- In #266, I'm adding an extra argument `exit_status` to method llvm func
- If the method is terminated by "a block with return", it stores `EXIT_RETURN` to `exit_status`
- Then `break` should also be handled this way
- But it is impossible if a lambda is invoked by `FnX#call`

Add HIR for lambda invocation

---

doc/guide/src/classes.md
doc/guide/src/expressions.md

Convenience spelling fixed in classes.md, also readonly changed to read-only for better readability.
In expressions.md,
- for the if statement `x if y` it states that x should be done if y is true.
-  for the unless statement `x unless y` it states that x should be done until y becomes true
So, some semantic changes

Some more typo fixes and doc fix.

---

.github/workflows/ubuntu.yml
Cargo.lock
Cargo.toml
README.md
src/cli.yml
src/code_gen/gen_exprs.rs
src/code_gen/mod.rs
src/corelib/mod.rs
src/hir/accessors.rs
src/hir/class_dict/indexing.rs
src/hir/class_dict/mod.rs
src/hir/class_dict/query.rs
src/hir/convert_exprs.rs
src/hir/hir_maker.rs
src/hir/hir_maker_context.rs
src/hir/mod.rs
src/hir/signature.rs
src/hir/sk_class.rs
src/lib.rs
src/library.rs
src/main.rs
src/mir/mod.rs
src/mir/vtable.rs
src/names.rs
src/runner.rs
src/ty.rs

fix #279 
This PR caches compilation of builtin/*.sk into builtin/builtin.bc and builtin/exports.json. 
builtin.bc contains LLVM bitcode and will be linked to main program with `clang` command.
exports.json contains information needed to compile the main program without reading builtin/*.sk. (JSON is used just for debugging purpose and is not intended to be modified in hand. We can change it to some binary format for better performance in the future.)

Precompile builtin/*.sk

---

Cargo.lock
Cargo.toml
src/code_gen/mod.rs
src/lib.rs
src/runner.rs
src/targets.rs

fix #281
This PR fixes clang's this warning
> warning: overriding the module target triple with x86_64-apple-macosx10.15.0 [-Woverride-module]
by explicitly passing `-target` to clang.

Fix macosx warning

---

builtin/hash.sk
src/ast.rs
src/code_gen/gen_exprs.rs
src/code_gen/mod.rs
src/code_gen/utils.rs
src/hir/class_dict/mod.rs
src/hir/class_dict/query.rs
src/hir/convert_exprs.rs
src/hir/hir_maker.rs
src/hir/hir_maker_context.rs
src/hir/mod.rs
src/mir/vtable.rs
src/names.rs
src/parser/definition_parser.rs
src/ty.rs
tests/sk/constants.sk

Implemented constant name resolution. For example this program no more raises error
```
class A
class B; end
def foo
B.new
end
end
```
refs #221

Resolve relative const

---

src/ast.rs
src/hir/class_dict/indexing.rs
src/hir/hir_maker.rs
src/parser/definition_parser.rs
src/parser/lexer.rs
src/parser/mod.rs
src/parser/token.rs

This PR adds `enum` keyword.  refs #142 
Its semantics are not completed yet. However I'd like to merge this now because I found #115 is needed for enums (for example, `class Maybe::Some<T> : class Maybe<T>`.)

Implementing enum part.1

---

builtin/error.sk
builtin/maybe.sk
builtin/result.sk
src/ast.rs
src/hir/class_dict/indexing.rs
src/parser/definition_parser.rs
tests/sk/enum.sk

In the case of `Result`, `Ok` and `Err` both have two type parameters
`V` and `E`. Then writing them in hand is just redundant.

feat!: Remove typarams from enum case

---

builtin/never.sk
src/ast.rs
src/corelib/mod.rs
src/hir/class_dict/class_index.rs
src/hir/class_dict/indexing.rs
src/hir/class_dict/mod.rs
src/hir/class_dict/query.rs
src/hir/convert_exprs.rs
src/hir/signature.rs
src/hir/superclass.rs
src/names.rs
src/parser/definition_parser.rs
src/runner.rs
src/ty.rs
tests/sk/nested_class.sk

This program compiles with this PR.
```rb
class A
class B; end
class C : B  # Superclass is A::B
def foo(b: B) # The type of B is A::B
end
end
end
```
Also, raise error for unknown typename instead of a compiler crash.
fix #221

impl. type name lookup in signatures and superclass

---

src/ast.rs
src/hir/convert_exprs.rs
src/hir/hir_maker.rs
src/hir/mod.rs
src/hir/sk_class.rs
src/names.rs
src/parser/definition_parser.rs
src/parser/expression_parser.rs
src/ty.rs
tests/expression_parser_test.rs

This PR changes interpretation of `A<B>` from `ConstRef("A<B>")` to `SpecializeExpression(ConstRef("A"), [ConstRef("B")])`.
motivation: #292

Angle operator

---

src/corelib/mod.rs
src/hir/class_dict/indexing.rs
src/hir/sk_class.rs

This PR denies inheriting from enum classes and enum case classes.
Also fixed cases with no params (eg. `Maybe::None`) had typarams (should have no typarams).

Disallow inheriting from enum.

---

builtin/_lambda.sk
builtin/array.sk
builtin/maybe.sk
builtin/result.sk
src/ast.rs
src/code_gen/mod.rs
src/parser/definition_parser.rs
src/parser/mod.rs
tests/expression_parser_test.rs
tests/sk/enum.sk

fix #296 
Rather than exporting all the `init_::XX` functions, only the new function `(package name)_init_constants` is exported.

Fix error `Undefined symbols _init_::None`

---

builtin/object.sk
src/code_gen/boxing.rs
src/code_gen/gen_exprs.rs
src/code_gen/mod.rs
src/code_gen/utils.rs
src/corelib/class.rs
src/corelib/object.rs
src/hir/convert_exprs.rs
src/hir/hir_maker.rs
src/names.rs
src/parser/definition_parser.rs
src/parser/expression_parser.rs
src/rustlib/src/sk_obj.rs
src/ty.rs

This PR implements `Object#class` method. 
- To achieve this, objects now have reference to its class object next to the vtable.
- Removed "internal constants"
- `#<class Void>` is stored in `::Void` and accessible by `Void.class` 
- `Object#==` now provides basic equality check (compare by pointer address)
fix #299

Object#class

---

src/code_gen/boxing.rs
src/code_gen/code_gen_context.rs
src/code_gen/gen_exprs.rs
src/code_gen/mod.rs
src/code_gen/utils.rs
src/code_gen/values.rs
src/corelib/array.rs
src/corelib/float.rs
src/corelib/int.rs
src/corelib/math.rs
src/corelib/object.rs
src/corelib/shiika_internal_memory.rs
src/corelib/shiika_internal_ptr.rs
src/hir/accessors.rs

This PR introduces some wrappers (`SkObj`, `I8Ptr`, etc) that wraps inkwell values to avoid simple mistakes.

refactor: Wrap inkwell values 

---

src/names.rs

At least this two struct's clone is not necessary for now.

refactor: remove unnecessary clone

---

src/hir/convert_exprs.rs
src/hir/ctx_stack.rs
src/hir/hir_maker.rs
src/hir/hir_maker_context.rs
src/hir/mod.rs

To implement pattern matching (#306), refactored `HirMaker` to have single stack of ctx (`CtxStack`) which contains all kinds of ctx (`enum HirMakerContext`).

Re-redesign ctx stack

---

Cargo.lock
Cargo.toml
builtin/_maybe.sk
builtin/array.sk
builtin/hash.sk
builtin/maybe.sk
src/hir/class_dict/query.rs
src/hir/convert_exprs.rs
src/hir/pattern_match.rs
src/runner.rs
src/type_checking/mod.rs
tests/sk/array.sk
tests/sk/generics.sk

This PR changes core class methods to return `Maybe` where they should.
Also includes these changes:
- Raise error when common ancestor falls back to `Object` (7764364) 
- Allow reassign `Some` to a variable contains `None` (3189cf8)
- Fix loading order of builtin/*.sk (5a9bafe)

Use `Maybe` in builtin classes

---

Cargo.lock
lib/shiika_ffi/Cargo.toml
lib/shiika_ffi/README.md
lib/shiika_ffi/src/lib.rs
lib/shiika_ffi_macro/Cargo.toml
lib/shiika_ffi_macro/README.md
lib/shiika_ffi_macro/src/lib.rs
lib/skc_codegen/Cargo.toml
lib/skc_codegen/src/boxing.rs
lib/skc_codegen/src/gen_exprs.rs
lib/skc_codegen/src/lambda.rs
lib/skc_codegen/src/lib.rs
lib/skc_codegen/src/utils.rs
lib/skc_rustlib/Cargo.toml
lib/skc_rustlib/src/builtin/array.rs
lib/skc_rustlib/src/builtin/float.rs
lib/skc_rustlib/src/builtin/int.rs
lib/skc_rustlib/src/builtin/math.rs
lib/skc_rustlib/src/builtin/object.rs
lib/skc_rustlib/src/builtin/shiika_internal_memory.rs
lib/skc_rustlib/src/builtin/shiika_internal_ptr.rs

This PR changes llvm function name for Shiika methods from `@"Array#push"` to `@Array_push`, for example.
I want to call Shiika methods from Rust (`skc_rustlib`) but Rust's `extern` does not allow us to use symbols other than `_` for function name.

Add crate for mangling Shiika methods

---

builtin/metaclass.sk
doc/guide/src/classes.md
lib/shiika_core/src/names.rs
lib/skc_ast2hir/src/class_dict/indexing.rs
lib/skc_ast2hir/src/hir_maker.rs
lib/skc_codegen/src/lib.rs
lib/skc_corelib/src/lib.rs
tests/sk/class_hierarchy.sk

This PR adds `Meta:Class` for `Class.class`.
To provide APIs like `Class.foo`, there should be `Meta:Class`.

Add Meta:Class

---

lib/skc_ast2hir/src/convert_exprs.rs
lib/skc_ast2hir/src/pattern_match.rs
lib/skc_codegen/src/gen_exprs.rs
lib/skc_codegen/src/lib.rs
tests/sk/class_hierarchy.sk

With this PR, `[1].class` returns `#<class Array<Int>>` which was returning `#<class Array>`. 
CI fails because `Some<T>.new` in `Array#first` creates an instance of `#<class Maybe::Some<T>>`. This will be fixed in next PR.

Fix class of generic objects

---

examples/fib.sk
examples/mandel.sk
examples/ray.sk
lib/skc_rustlib/src/builtin/object.rs

This PR fixes examples/*.sk which used removed methods (putd, putchar).
This PR also make `Object#print` flush stdout for concenience.
(In the future there should be a method with better performance which prints without flushing)

fix broken examples

---

builtin/object.sk
lib/skc_ast2hir/src/convert_exprs/method_call.rs

This PR adds `Object#unsafe_cast`. It does nothing at runtime but forces the receiver type recognized by the compiler.
For workarounds of compiler bugs.
In the future, this may be useful with some meta-programming stuffs. Also, may require being enclosed by "unsafe block" (like Rust).

impl. unsafe_cast

---

src/targets.rs

.os_version() returns "12.3" for example but clang expects "12.3.0"
fix #281

targets: Add .0 for clang warning

---

builtin/array.sk
lib/shiika_parser/src/lexer.rs

This PR fixes parser so that it can parse `empty?` as a method call with implicit self.

fix: fails to parse `if empty?`

---

builtin/array.sk
lib/skc_rustlib/provided_methods.json5
lib/skc_rustlib/src/builtin/array.rs
lib/skc_rustlib/src/builtin/class.rs
lib/skc_rustlib/src/builtin/int.rs
lib/skc_rustlib/src/builtin/object.rs

This PR replaces implementation of `Array` with Rust's `Vec`.

builtin: re-impl. Array with Rust `Vec`

---

builtin/object.sk
lib/skc_rustlib/provided_methods.json5
lib/skc_rustlib/src/builtin/object.rs

This PR moves `Object#panic` from ./builtin to skc_rustlib. By calling Rust's `panic!`, backtrace is shown with `RUST_BACKTRACE=1`. Example:
```
/Users/yhara/proj/shiika % RUST_BACKTRACE=1 cargo run -- run ~/proj/BidirectionalTypechecking/bidi.sk
Finished dev [unoptimized + debuginfo] target(s) in 0.06s
Running `/Users/yhara/tmp/cargo_target/debug/shiika run /Users/yhara/proj/BidirectionalTypechecking/bidi.sk`
warning: overriding the module target triple with arm64-apple-macosx12.0.0 [-Woverride-module]
1 warning generated.
warning: overriding the module target triple with arm64-apple-macosx12.0.0 [-Woverride-module]
1 warning generated.
thread '<unnamed>' panicked at 'no matching clause found', lib/skc_rustlib/src/builtin/object.rs:63:5
stack backtrace:
0: rust_begin_unwind
at …
```

Move `Object#panic` to rustlib

---

builtin/array.sk
builtin/dict.sk
builtin/enumerable.sk
builtin/int.sk
builtin/result.sk
builtin/string.sk
lib/shiika_ast/src/lib.rs
lib/shiika_core/src/ty/term_ty.rs
lib/shiika_parser/src/definition_parser.rs
lib/shiika_parser/src/expression_parser.rs
lib/skc_ast2hir/src/class_dict/found_method.rs
lib/skc_ast2hir/src/class_dict/indexing.rs
lib/skc_ast2hir/src/class_dict/query.rs
lib/skc_ast2hir/src/convert_exprs.rs
lib/skc_ast2hir/src/convert_exprs/block.rs
lib/skc_ast2hir/src/convert_exprs/method_call.rs
lib/skc_ast2hir/src/convert_exprs/params.rs
lib/skc_ast2hir/src/hir_maker.rs
lib/skc_ast2hir/src/type_system/subtyping.rs
lib/skc_ast2hir/src/type_system/type_checking.rs
lib/skc_hir/src/signature.rs

With this PR, type annotations are no more mandatory for block parameters. For example: d304868f646af4bd612da040a7725ebf52186e3d

Infer block param

---

lib/shiika_ast/src/location.rs
lib/shiika_parser/src/ast_builder.rs
lib/shiika_parser/src/definition_parser.rs
lib/shiika_parser/src/expression_parser.rs
lib/skc_ast2hir/src/convert_exprs.rs
lib/skc_ast2hir/src/pattern_match.rs
lib/skc_ast2hir/src/type_system/type_checking.rs
lib/skc_corelib/src/lib.rs
lib/skc_hir/src/lib.rs

This PR contains several fixes around LocationSpan.
refs #251

Better handling of LocationSpan::todo

---

src/loader.rs

This PR fixes compile error when there are comments or empty lines between require's. eg:
```
require "./a.sk"
require "./b.sk"
```

fix: should skip comments between require's

---

Cargo.lock
lib/shiika_ffi_macro/Cargo.toml
lib/shiika_ffi_macro/README.md
lib/shiika_ffi_macro/src/lib.rs
lib/shiika_ffi_macro/src/shiika_method_ref.rs
lib/skc_rustlib/src/builtin/array.rs
lib/skc_rustlib/src/builtin/class.rs
lib/skc_rustlib/src/lib.rs
lib/skc_rustlib/src/sk_methods.rs

This PR adds proc macro `shiika_method_ref` so that changes of mangling rule does not affect Shiika libraries written in Rust.

Add proc macro for calling Shiika method

---

lib/shiika_core/src/names/class_name.rs
lib/shiika_core/src/names/method_name.rs
lib/shiika_core/src/ty.rs
lib/skc_ast2hir/src/accessors.rs
lib/skc_ast2hir/src/class_dict.rs
lib/skc_ast2hir/src/class_dict/indexing.rs
lib/skc_ast2hir/src/convert_exprs.rs
lib/skc_ast2hir/src/ctx_stack.rs
lib/skc_ast2hir/src/hir_maker.rs
lib/skc_ast2hir/src/pattern_match.rs
lib/skc_ast2hir/src/rustlib_methods.rs
lib/skc_codegen/src/boxing.rs
lib/skc_codegen/src/gen_exprs.rs
lib/skc_hir/src/signature.rs

This PR replaces MethodFullname::class_name with ::type_name.

refactor: MethodFullname should have a TypeFullname 

---

lib/shiika_ffi/src/lib.rs
lib/skc_codegen/src/gen_exprs.rs
lib/skc_codegen/src/lib.rs
lib/skc_codegen/src/utils.rs

This PR removes colons(`::`) from linker-level name of Shiika constants so that it can be referred with Rust's `extern`.

Const name mangling

---

lib/shiika_core/src/ty.rs
lib/shiika_core/src/ty/lit_ty.rs
lib/shiika_core/src/ty/typaram_ref.rs
lib/skc_ast2hir/src/convert_exprs.rs
lib/skc_ast2hir/src/convert_exprs/block.rs
lib/skc_ast2hir/src/convert_exprs/method_call.rs
lib/skc_ast2hir/src/convert_exprs/params.rs
lib/skc_ast2hir/src/lib.rs
lib/skc_ast2hir/src/type_inference.rs
lib/skc_ast2hir/src/type_inference/method_call_inf.rs
lib/skc_ast2hir/src/type_inference/tmp_ty.rs
lib/skc_ast2hir/src/type_system/type_checking.rs
lib/skc_hir/src/signature.rs

With this PR,
[1,2,3].map<String>{|i| i.to_s}
can just be
[1,2,3].map{|i| i.to_s}

impl. method tyargs inferrence

---

lib/shiika_ast/src/lib.rs
lib/shiika_parser/src/ast_builder.rs
lib/shiika_parser/src/expression_parser.rs
lib/skc_ast2hir/src/convert_exprs.rs
lib/skc_ast2hir/src/convert_exprs/method_call.rs
tests/sk/ivar.sk

This PR adds new syntax `(expr)(args, ...)` for example, `(@f)(1)` where `@f` is a function (instance of `Fn1`).

impl. parenthesized function call

---

lib/skc_ast2hir/src/convert_exprs.rs
lib/skc_ast2hir/src/type_system/type_checking.rs
tests/sk/enum.sk

This PR raises error (instead of crashing) for program like this:
```
Dict<Int>.new   # should be Dict<String, Int>
```

Check number of type arguments

---

lib/shiika_core/src/ty/lit_ty.rs
lib/shiika_core/src/ty/term_ty.rs
lib/skc_ast2hir/src/class_dict.rs
lib/skc_ast2hir/src/class_dict/build_wtable.rs
lib/skc_ast2hir/src/class_dict/indexing.rs
lib/skc_ast2hir/src/class_dict/query.rs
lib/skc_ast2hir/src/type_system/subtyping.rs
lib/skc_hir/src/sk_type/sk_class.rs
lib/skc_hir/src/superclass.rs

This PR fixes this TODO in superclass.rs.
> // TODO: the content should be LitTy rather than TermTy

refactor: Changed content of Superclass

---

Cargo.lock
Cargo.toml
lib/skc_codegen/Cargo.toml
lib/skc_codegen/src/lib.rs
lib/skc_codegen/src/wtable.rs

This PR updates inkwell (to use `Context::get_struct_type` useful for #433.)

Upgrade inkwell

---

builtin/fn.sk
lib/skc_ast2hir/src/convert_exprs.rs
lib/skc_ast2hir/src/convert_exprs/method_call.rs
lib/skc_ast2hir/src/hir_maker_context.rs
lib/skc_codegen/src/code_gen_context.rs
lib/skc_codegen/src/gen_exprs.rs
lib/skc_codegen/src/lambda.rs
lib/skc_codegen/src/lib.rs
lib/skc_codegen/src/utils.rs
lib/skc_codegen/src/values.rs
lib/skc_corelib/src/fn_x.rs
lib/skc_hir/src/lib.rs

Currently lambda captures are represented in Shiika Array (`Array<Object>`). It means that LLVM cannot check its length nor the item types. This PR makes it easier to debug bugs like #432.
- codegen
- mir
- maybe we want to preprocess lambdas because we do not want to traverse the HIR twice (once for creating lambda funcs, once for lambda captures)

Each lambda captures should have its own LLVM type

---

lib/skc_rustlib/provided_methods.json5
lib/skc_rustlib/src/builtin/shiika_internal_ptr.rs

This PR adds `Shiika::Internal::Ptr.p` for debugging memory corruption bugs.
`Shiika::Internal::Ptr.p(1, 3)`
shows
```
0x101456580: 1010462d0    # Addr of the vtable
0x101456588: 101453e40    # Addr of #<class Int>
0x101456590: 1   # The wrapped value
```

Add Shiika::Internal::Ptr.p

---

.github/workflows/ci.yml
lib/shiika_parser/src/lexer.rs
lib/skc_codegen/src/utils.rs
src/runner.rs

CI: Add MacOs to runs-on, add rust fmt check

---

lib/skc_rustlib/src/builtin/file.rs
lib/skc_rustlib/src/builtin/object.rs
lib/skc_rustlib/src/builtin/result.rs
lib/skc_rustlib/src/builtin/void.rs

This PR changes `SkResult` to `SkResult<T>` so that it can be handled more safely in Rust.

Add type parameter to SkResult

---

lib/shiika_ast/src/lib.rs
lib/shiika_ast/src/token.rs
lib/shiika_parser/src/ast_builder.rs
lib/shiika_parser/src/definition_parser.rs
lib/shiika_parser/src/expression_parser.rs
lib/shiika_parser/src/lexer.rs
lib/skc_ast2hir/src/convert_exprs.rs
lib/skc_ast2hir/src/convert_exprs/method_call.rs
lib/skc_ast2hir/src/error.rs
tests/sk/method_call.sk

This PR allows specifying method argument by name. For example:
```
foo(1, 2, c: 3, d: 4)
```
Unlike Ruby, there is no difference on the definition side. In other words, any argument is considered a keyword argument.

new feature: Method call with named arguments

---

Cargo.lock
lib/shiika_core/src/names/method_name.rs
lib/shiika_core/src/ty/lit_ty.rs
lib/shiika_core/src/ty/term_ty.rs
lib/shiika_core/src/ty/typaram.rs
lib/shiika_core/src/ty/typaram_ref.rs
lib/skc_hir/Cargo.toml
lib/skc_hir/src/signature.rs
lib/skc_mir/src/library.rs
lib/skc_mir/src/vtable.rs
lib/skc_mir/src/vtables.rs
src/runner.rs

This PR reduces size of exports.json by customizing how MethodSignature is serialized.

Simplify JSON representation of MethodSignature

---

lib/skc_ast2hir/src/convert_exprs.rs
lib/skc_ast2hir/src/hir_maker_context.rs
lib/skc_codegen/src/gen_exprs.rs
lib/skc_codegen/src/lambda.rs
lib/skc_codegen/src/utils.rs
lib/skc_hir/src/lib.rs
tests/sk/lambda.sk

This PR fixes compiler to generate right code for nested closure like this.
```sk
class UpdateFromNestedClosure
def self.run
var a = 0
[1].each do |i|
[1].each do |j|
a = 1
end
end
unless a == 1; puts "ng UpdateFromNestedClosure"; end
end
end
UpdateFromNestedClosure.run
```

fix compilation error on nested closure

---

.gitignore
lib/skc_ast2hir/src/convert_exprs.rs
lib/skc_ast2hir/src/ctx_stack.rs
lib/skc_ast2hir/src/hir_maker.rs
lib/skc_ast2hir/src/hir_maker_context.rs
lib/skc_codegen/src/gen_exprs.rs
lib/skc_codegen/src/lambda.rs
lib/skc_codegen/src/lib.rs
lib/skc_hir/src/lib.rs

#388 
- Create the ```If(IfCtx)``` in [lib/skc_ast2hir/src/hir_maker_context.rs](https://github.com/shiika-lang/shiika/compare/main...EruEri:388-if-should-make-local-variable-scope?expand=1#diff-ac6ca6d685563ab3a1d75011b4737d4399d505188617b2c1d1659b92cd509ce6)
- Push and pop context in [lib/skc_ast2hir/src/convert_exprs.rs](https://github.com/shiika-lang/shiika/compare/main...EruEri:388-if-should-make-local-variable-scope?expand=1#diff-219b4f566d13c9455fa437e87302feb4588b53d8a5cb92ee329407c5cd9c114a)

388 if should make local variable scope

---

lib/skc_codegen/src/gen_exprs.rs
tests/sk/loops_and_jumps.sk

This PR fixes #484.
```
"he\nllo".each_char do |b|
p b
break if b == "\n"
end
```
1. This code calls `#each_char` with a lambda (say, lambda1).
2. `#each_char` calls `Integer#times` with a lambda (say, lambda2).
3. lambda2 invokes lambda1.
4. lambda1 ends with `break`.
5. lambda2 also should end with `break`.

Forward exit_status in lambda in lambda

---

lib/shiika_core/src/names/type_name.rs
lib/shiika_core/src/ty.rs
lib/shiika_core/src/ty/term_ty.rs
lib/shiika_core/src/ty/typaram_ref.rs
lib/skc_ast2hir/src/convert_exprs.rs
lib/skc_ast2hir/src/hir_maker.rs
lib/skc_ast2hir/src/pattern_match.rs

This PR changes the type of `TermTy::fullname` to `TypeFullname`.

refactor: Change TermTy::fullname to be TypeFullname

---

builtin/maybe.sk
lib/skc_ast2hir/src/class_dict/found_method.rs
lib/skc_ast2hir/src/class_dict/indexing.rs
lib/skc_ast2hir/src/class_dict/query.rs
lib/skc_ast2hir/src/convert_exprs.rs
lib/skc_ast2hir/src/convert_exprs/method_call.rs
lib/skc_ast2hir/src/hir_maker.rs
lib/skc_ast2hir/src/type_inference/method_call_inf.rs
lib/skc_ast2hir/src/type_inference/tmp_ty.rs
lib/skc_hir/src/signature.rs
lib/skc_hir/src/sk_method.rs

For the first step of #483, this PR adds type parameters to the signature of `.new`.
- `Array.new` takes type parameter so `Array.new<Int>` is legal now
- This yields the same result as `Array<Int>.new`
- Iplementation
- At the end of convert_method_call, if the called method is `Array.new<Int>`, generate HIR for `Array<Int>.new` instead
- In the llvm layer they are the same function (`@Meta_Array_new`) but the first argument should be `Array<Int>` because it is set to the .class of the new instance.

Add typarams to .new

---

builtin/array.sk
builtin/dict.sk
builtin/enumerable.sk
builtin/file.sk
builtin/maybe.sk
builtin/readable.sk

This PR removes omittable type arguments from builtin/*.sk.
The only exception is `Enumerable#flat_map`; I got a compile error when I removed the type arguments. I'll fix it by another PR.

Remove omittable type arguments

---

builtin/enumerable.sk
lib/skc_ast2hir/src/convert_exprs/method_call.rs
lib/skc_ast2hir/src/type_system/type_checking.rs
lib/skc_hir/src/signature.rs

This PR removes the following explicit type argument in `Enumerable#flat_map`
```
self.map<Array<R>>(f).fold(Array<R>.new){|sum: Array<R>, item: Array<R>|
~~~~~~~~~~
```
and fixes a type error that prevent this to work.

Remove tyarg in flat_map

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
lib/skc_ast2hir/src/accessors.rs
lib/skc_codegen/Cargo.toml
lib/skc_codegen/src/boxing.rs
lib/skc_codegen/src/code_gen_context.rs
lib/skc_codegen/src/gen_exprs.rs
lib/skc_codegen/src/lambda.rs
lib/skc_codegen/src/lib.rs
lib/skc_codegen/src/utils.rs
lib/skc_codegen/src/values.rs
lib/skc_codegen/src/vtable.rs
lib/skc_codegen/src/wtable.rs
lib/skc_corelib/src/fn_x.rs
lib/skc_corelib/src/lib.rs
lib/skc_corelib/src/shiika_internal_ptr.rs
lib/skc_hir/src/sk_method.rs
lib/skc_hir/src/sk_type.rs
src/runner.rs

This PR upgrades LLVM to v15.
The biggest change is that llvm pointer types no more holds the pointee type. https://llvm.org/docs/OpaquePointers.html
As a consequence, `build_load` API needs the pointee type (i.e. the type of the value to load.)
Considering all Shiika values (formerly `%Object*` or `%Bool*`, etc) are now a `ptr` type, we could make codegen simpler but I'll try it later.

Upgrade llvm to llvm-15

---

lib/skc_codegen/src/boxing.rs
lib/skc_codegen/src/gen_exprs.rs
lib/skc_codegen/src/lib.rs
lib/skc_codegen/src/utils.rs

This PR removes unneeded bitcast in allocate_llvm_obj. The argument `reg_name` is also removed by tihs change.

Remove bitcast after allocate_llvm_obj

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
README.md
doc/guide/src/install.md
lib/skc_codegen/Cargo.toml

This PR upgrades llvm from 15 to 16.

Upgrade to llvm 16

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
README.md
doc/guide/src/install.md
lib/skc_ast2hir/src/accessors.rs
lib/skc_codegen/Cargo.toml
lib/skc_codegen/src/boxing.rs
lib/skc_codegen/src/code_gen_context.rs
lib/skc_codegen/src/gen_exprs.rs
lib/skc_codegen/src/lambda.rs
lib/skc_codegen/src/lib.rs
lib/skc_codegen/src/utils.rs
lib/skc_codegen/src/values.rs
lib/skc_codegen/src/vtable.rs
lib/skc_codegen/src/wtable.rs
lib/skc_corelib/src/fn_x.rs
lib/skc_corelib/src/lib.rs
lib/skc_corelib/src/shiika_internal_ptr.rs
lib/skc_hir/src/sk_method.rs
lib/skc_hir/src/sk_type.rs

Upgrade LLVM to 15+

---

lib/skc_ast2hir/src/convert_exprs.rs
lib/skc_ast2hir/src/hir_maker.rs
lib/skc_ast2hir/src/pattern_match.rs
lib/skc_ast2hir/src/type_system/type_checking.rs
lib/skc_codegen/src/gen_exprs.rs
lib/skc_codegen/src/lambda.rs
lib/skc_codegen/src/lib.rs
lib/skc_hir/src/lib.rs
lib/skc_hir/src/pattern_match.rs
lib/skc_hir/src/sk_method.rs

This PR removes `HirExpressions` from HIR.
`HirExpressions` expresses serial execution of some exprs but it can be done by `HirParenthesizedExpr`. Codegen is now a bit simpler by removing `gen_exprs`.

Remove HirExpressions

---

lib/skc_codegen/src/boxing.rs
lib/skc_codegen/src/gen_exprs.rs
lib/skc_codegen/src/lambda.rs
lib/skc_codegen/src/lib.rs
lib/skc_codegen/src/utils.rs
lib/skc_codegen/src/values.rs
lib/skc_codegen/src/vtable.rs
lib/skc_codegen/src/wtable.rs

This PR simplify codegen by removing arguments unnecessary after LLVM 15.

Remove argument `ty` from gen.llvm_type

---

lib/skc_codegen/src/lambda.rs
lib/skc_codegen/src/lib.rs
lib/skc_hir/src/lib.rs
lib/skc_hir/src/visitor.rs

This PR simplifies duplicated codes on traversing a HIR tree.

Introduce visitor pattern

---

builtin/error.sk
builtin/file.sk
builtin/readable.sk
builtin/result.sk
lib/shiika_ast/src/lib.rs
lib/skc_ast2hir/src/class_dict/indexing.rs
lib/skc_ast2hir/src/class_dict/type_index.rs
tests/sk/enum.sk

This PR removes unused type parameters from enum cases. For example, `Result::Fail<V>` is changed to just `Result::Fail` because `Fail` does not depend on `V`.
```
enum Result<V>
case Ok(value: V)
case Fail(err: Error)
```

breaking change: Remove unused type parameters from enum case

---

lib/skc_ast2hir/src/convert_exprs/method_call.rs

#505 
- Fix the unwrap none when a method/function is called with 0 argument but expect more

Empty args compiler crash 

---

builtin/file.sk
builtin/readable.sk
builtin/result.sk
lib/shiika_parser/src/lexer.rs
lib/skc_ast2hir/src/convert_exprs.rs
lib/skc_ast2hir/src/convert_exprs/method_call.rs
lib/skc_ast2hir/src/error.rs
lib/skc_ast2hir/src/pattern_match.rs
tests/sk/result.sk

This PR implements pseudo-method `try!`.
foo.try!
is equivalent to
```sk
match foo
when Ok(v) then v
when e return e
end
```

impl. Result#try!

---

src/cli.rs

```
$ cargo run
subcommand 0.9.1
...
```
```
$ cargo run
shiika 0.9.1
...
```

fix command name

---

builtin/string.sk
lib/skc_rustlib/src/builtin/array.rs
lib/skc_rustlib/src/builtin/class.rs
lib/skc_rustlib/src/builtin/string.rs
lib/skc_rustlib/src/lib.rs
lib/skc_rustlib/src/sk_cls.rs

This PR fixes a SEGV occurs by `"foo".chars.reverse"`, for example.
`chars` is implemented in Rust and calls `SkAry::new`. I forgot to give appropreate arg for `meta_array_new` and broken object was created.

Fix String#chars

---

builtin/math.sk
lib/skc_ast2hir/src/class_dict/indexing.rs

close #416
Current codes runs well, but I don't know if I missed some fields in the todo entry.
And then add other fields in `math.sk`, `build-corelib` will panic:
```
thread 'main' panicked at lib/skc_ast2hir/src/hir_maker.rs:457:17:
[BUG] signature not found (Math/a)
stack backtrace:
0: _rust_begin_unwind
1: core::panicking::panic_fmt
2: skc_ast2hir::hir_maker::HirMaker::convert_method_def_::{{closure}}
at ./lib/skc_ast2hir/src/hir_maker.rs:457:17
3: core::option::Option<T>::unwrap_or_else
at /private/tmp/rust-20231125-5709-3eoq7y/rustc-1.74.0-src/library/core/src/option.rs:979:21
4: skc_ast2hir::hir_maker::HirMaker::convert_method_def_
at ./lib/skc_ast2hir/src/hir_maker.rs:453:25
5: skc_ast2hir::hir_maker::HirMaker::convert_method_def
at ./lib/skc_ast2hir/src/hir_maker.rs:440:35
6: …
```

define Math as a module instead of class

---

lib/skc_async_experiment/src/codegen.rs
lib/skc_async_experiment/src/codegen/intrinsics.rs
lib/skc_async_experiment/src/hir.rs
lib/skc_async_experiment/src/hir/expr.rs
lib/skc_async_experiment/src/hir/rewriter.rs
lib/skc_async_experiment/src/hir/typing.rs
lib/skc_async_experiment/src/hir/untyped.rs
lib/skc_async_experiment/src/hir/visitor.rs
lib/skc_async_experiment/src/hir_lowering/async_splitter.rs
lib/skc_async_experiment/src/verifier.rs

This PR implements `if` for the new runtime.
refs #545

new_runtime: impl. if

---

Cargo.lock
lib/skc_async_experiment/Cargo.toml
lib/skc_async_experiment/src/hir.rs
lib/skc_async_experiment/src/hir/expr.rs
lib/skc_async_experiment/src/hir/ty.rs
lib/skc_async_experiment/src/hir/typing.rs
lib/skc_async_experiment/src/hir/untyped.rs
lib/skc_async_experiment/src/hir_to_mir.rs
lib/skc_async_experiment/src/prelude.rs
lib/skc_async_experiment/src/run.rs

This PR replaces hir::Ty with shiika_core::ty::TermTy.

new_runtime: Remove hir::Ty

---

Cargo.lock
lib/skc_async_experiment/Cargo.toml
lib/skc_async_experiment/src/build.rs
lib/skc_async_experiment/src/build/compiler.rs
lib/skc_async_experiment/src/build/exe_builder.rs
lib/skc_async_experiment/src/build/lib_builder.rs
lib/skc_async_experiment/src/build/loader.rs
lib/skc_async_experiment/src/cli.rs
lib/skc_async_experiment/src/codegen.rs
lib/skc_async_experiment/src/codegen/constants.rs
lib/skc_async_experiment/src/hir.rs
lib/skc_async_experiment/src/hir/typing.rs
lib/skc_async_experiment/src/hir/untyped.rs
lib/skc_async_experiment/src/hir_to_mir.rs
lib/skc_async_experiment/src/hir_to_mir/constants.rs
lib/skc_async_experiment/src/mir.rs
lib/skc_async_experiment/src/mir/ty.rs
lib/skc_async_experiment/src/mir/visitor.rs
lib/skc_async_experiment/src/mir_lowering/async_splitter.rs
lib/skc_async_experiment/src/mir_lowering/pass_async_env.rs
lib/skc_async_experiment/src/mir_lowering/resolve_env_op.rs
lib/skc_async_experiment/src/package.rs
lib/skc_async_experiment/src/prelude.rs
lib/skc_hir/src/sk_type.rs
lib/skc_hir/src/sk_type/sk_type_base.rs
lib/skc_mir/src/library.rs
packages/core/index.sk

This PR allows .sk to use constants defined in dependent packages.

new_runtime: Accessing package const

---

Cargo.lock
Cargo.toml

This PR removes `atty` from dependency (alerted by Dependabot).

Remove atty crate from dependency (unmaintained)
