shiika-lang/shiika

CHANGELOG.md, src/parser/expression_parser.rs
=> fix: Parse a*b*c (refs #5)

CHANGELOG.md, src/ast.rs, src/code_gen/mod.rs, src/hir/hir_maker.rs, src/hir/mod.rs, src/parser/definition_parser.rs, src/parser/expression_parser.rs
=> Support `if` with multiple stmts

src/code_gen/mod.rs
=> refactor: Split user_main

examples/hello.sk, src/ast.rs, src/code_gen/mod.rs, src/hir/hir_maker.rs, src/hir/mod.rs, src/parser/expression_parser.rs, src/parser/lexer.rs, src/parser/token.rs, src/stdlib/mod.rs, src/stdlib/object.rs
=> Add String class

src/code_gen/mod.rs, src/hir/hir_maker.rs, src/hir/mod.rs, src/stdlib/shiika_internal_memory.rs
=> Extract constant initialization from UserMain

corelib/mutable_string.sk, corelib/string.sk, src/code_gen/mod.rs, src/hir/hir_maker.rs, src/hir/index.rs, src/hir/mod.rs, src/main.rs, src/names.rs, src/stdlib/mod.rs, src/stdlib/object.rs, src/stdlib/shiika_internal_memory.rs, src/stdlib/string.rs
- String, MutableString
- Call initialize from .new
=> Impl. String#+

src/code_gen/mod.rs, src/corelib/mod.rs, src/hir/hir_maker.rs, src/hir/index.rs, src/hir/mod.rs, src/names.rs
=> Impl. Class#name

examples/ray.sk, src/code_gen/mod.rs, src/corelib/float.rs.erb, src/corelib/int.rs.erb, src/corelib/mod.rs, src/hir/hir_maker.rs, src/hir/mod.rs, src/parser/definition_parser.rs, src/parser/lexer.rs, src/parser/mod.rs, src/parser/token.rs, src/type_checking/mod.rs
=> Add ray.sk and fixes for it

builtin/mutable_string.sk, src/ast.rs, src/code_gen/mod.rs, src/hir/hir_maker.rs, src/hir/mod.rs, src/parser/expression_parser.rs
=> Mutable ivar

src/code_gen/gen_exprs.rs
=> fix(code_gen): Logical not is broken

tests/integration_test.rs, tests/sk/ivar.sk
=> test: Write integraiton test in Shiika

src/parser/expression_parser.rs, tests/sk/logical_operator.sk
=> fix(parser): fix not operator

.github/workflows/ubuntu.yml, src/lib.rs, tests/integration_test.rs
This pull-request makes [test Shiika on GitHub Actions](https://github.com/nishidayuya/shiika/runs/724080286)!
Contains:
* Define GitHub Actions workflow
* Remove distribution-dependent code from tests/integration_test.rs
* By environment variables
refs #63
=> ci: Use GitHub Actions

src/main.rs
=> fix error #88 (examples not compile in Linux)

src/code_gen/gen_exprs.rs, src/code_gen/mod.rs, src/corelib/float.rs.erb, src/corelib/int.rs.erb, src/corelib/math.rs, src/corelib/object.rs, tests/sk/float.sk
=> feat: Changed Float to struct

src/code_gen/boxing.rs, src/code_gen/gen_exprs.rs, src/code_gen/mod.rs, src/corelib/float.rs.erb, src/corelib/int.rs.erb, src/corelib/object.rs, src/corelib/shiika_internal_memory.rs, src/corelib/shiika_internal_ptr.rs
=> Changed Int to struct

tests/integration_test.rs, tests/sk/float.sk, tests/sk/inheritance.sk, tests/sk/ivar.sk, tests/sk/logical_operator.sk, tests/sk/loops_and_conditionals.sk, tests/sk/nested_class.sk
=> tests: Add "puts ok"

builtin/array.sk, src/code_gen/gen_exprs.rs, src/corelib/shiika_internal_ptr.rs, src/parser/expression_parser.rs, tests/integration_test.rs, tests/sk/array.sk
=> CodeGen for array literal

.github/workflows/ubuntu.yml, src/code_gen/mod.rs, src/error.rs, src/lib.rs, src/main.rs, src/parser/base.rs, src/runner.rs, tests/integration_test.rs
=> Merge code runner

builtin/array.sk, src/code_gen/gen_exprs.rs, src/hir/convert_exprs.rs, src/hir/hir_maker.rs, src/hir/mod.rs
=> Fix codegen for non-Object array

builtin/array.sk, src/ast.rs, src/corelib/mod.rs, src/hir/class_dict.rs, src/hir/sk_class.rs, src/parser/definition_parser.rs, src/parser/expression_parser.rs, src/parser/lexer.rs, src/parser/token.rs, src/ty.rs
=> Parse type parameters

builtin/array.sk, src/code_gen/gen_exprs.rs, src/corelib/mod.rs, src/corelib/shiika_internal_ptr.rs, src/hir/class_dict/indexing.rs, src/hir/class_dict/mod.rs, src/hir/hir_maker.rs, src/hir/mod.rs, src/hir/signature.rs, src/names.rs, src/ty.rs
=> Array#first

src/hir/class_dict/indexing.rs, src/hir/class_dict/mod.rs, src/hir/class_dict/query.rs, src/hir/convert_exprs.rs, src/hir/hir_maker.rs, src/hir/signature.rs, src/ty.rs
=> Add proper type for the result of Array#first

src/runner.rs, tests/integration_test.rs
=> fix(runner): `shiika run` should not capture output

src/code_gen/boxing.rs, src/code_gen/gen_exprs.rs, src/code_gen/mod.rs, src/corelib/float.rs.erb, src/corelib/int.rs.erb, src/corelib/lambda.rs, src/corelib/math.rs, src/corelib/mod.rs, src/corelib/object.rs, src/corelib/shiika_internal_memory.rs, src/corelib/shiika_internal_ptr.rs, src/hir/accessors.rs
=> impl. Fn1#call

src/code_gen/code_gen_context.rs, src/code_gen/gen_exprs.rs, src/code_gen/mod.rs, src/hir/convert_exprs.rs, tests/sk/lambda.sk
=> Support calling anon-funcs

builtin/array.sk, builtin/lambda.sk, src/code_gen/gen_exprs.rs, src/code_gen/lambda.rs, src/code_gen/utils.rs, src/corelib/fn_x.rs, src/corelib/mod.rs, src/hir/convert_exprs.rs, src/hir/mod.rs, src/ty.rs, tests/sk/lambda.sk
=> impl. capturing free variables in lambda

doc/shg/src/SUMMARY.md, doc/shg/src/perf.md, src/code_gen/boxing.rs, src/code_gen/gen_exprs.rs, src/code_gen/mod.rs, src/code_gen/utils.rs, src/corelib/float.rs, src/corelib/int.rs, tests/sk/lambda.sk
=> Support capturing bools

src/hir/convert_exprs.rs, src/hir/hir_maker_context.rs
=> fix(hir_maker): toplevel var captured by a method

builtin/array.sk
This is a very basic strategy to growth the capacity of array, but I think it works for now.
close #107﻿
=> feat(builtin): growth array capacity if necessary

builtin/object.sk, src/code_gen/mod.rs, src/corelib/object.rs
=> Exit and panic

src/parser/expression_parser.rs
Issue: https://github.com/yhara/shiika/pull/163#issuecomment-706716804
=> Erase wrong comments.

src/hir/class_dict/query.rs, src/hir/convert_exprs.rs, src/hir/hir_maker.rs, src/hir/mod.rs, src/ty.rs, src/type_checking/mod.rs, tests/sk/virtual_method.sk
=> Allow passing descendant objects

src/parser/expression_parser.rs, src/parser/lexer.rs, src/parser/token.rs, tests/sk/plus-eq.sk, tests/sk/xxx-eq.sk
=> Add `-=`, `*=`, `/=`, `%=`, `<<=`, `>>=`, `&=`, `|=`, `^=`, `&&=`, `||=`,

src/code_gen/boxing.rs, src/code_gen/code_gen_context.rs, src/code_gen/gen_exprs.rs, src/code_gen/lambda.rs, src/code_gen/mod.rs, src/corelib/mod.rs, src/hir/accessors.rs, src/hir/convert_exprs.rs, src/hir/hir_maker.rs, src/hir/hir_maker_context.rs, src/hir/mod.rs
=> Allocate local variables only once

README.md, builtin/array.sk, builtin/string.sk, src/code_gen/gen_exprs.rs, src/corelib/shiika_internal_ptr.rs, src/hir/hir_maker.rs, tests/sk/string.sk
impl. String#==, #slice_bytes, #split
=> String#split

src/parser/lexer.rs
=> feat(parser): Escape sequence

builtin/array.sk, src/hir/convert_exprs.rs, src/hir/hir_maker.rs, src/hir/hir_maker_context.rs, tests/sk/lambda.sk
=> Fix refer arg from block

src/parser/base.rs, src/parser/expression_parser.rs, src/parser/lexer.rs, tests/sk/generics.sk
=> Parse `A<B<C>>`

src/ast.rs, src/code_gen/gen_exprs.rs, src/code_gen/mod.rs, src/corelib/float.rs, src/corelib/int.rs, src/corelib/object.rs, src/corelib/shiika_internal_ptr.rs, src/hir/mod.rs
In the future Int should automatically extended to BigInt (like Ruby). As for now, use i64 to handle bigger number
=> Use i64 for Int

builtin/mutable_string.sk, builtin/string.sk, src/hir/convert_exprs.rs
=> Check reassign to outer readonly variable

src/code_gen/boxing.rs, src/code_gen/mod.rs
With this PR .ll will be much more readable
=> refactor: Add llvm funcs about boxing

builtin/array.sk, src/code_gen/gen_exprs.rs, src/parser/definition_parser.rs, src/parser/expression_parser.rs, src/parser/lexer.rs, src/parser/token.rs, tests/sk/array.sk, tests/sk/string.sk
Note: `foo[bar, baz]` is not supported by this PR
refs #155
=> feat: Parse `foo[bar]`

src/code_gen/gen_exprs.rs, src/hir/convert_exprs.rs, src/hir/mod.rs
=> feat: Refer ivar from a block

.github/workflows/ubuntu.yml, Cargo.lock, Cargo.toml, README.md
=> chores: Upgrade to llvm 9

builtin/array.sk, builtin/mutable_string.sk, src/code_gen/gen_exprs.rs, src/hir/convert_exprs.rs, src/hir/hir_maker.rs, src/hir/mod.rs, src/names.rs
Fixed lookup of nested constants
=> Nested const

builtin/array.sk, src/hir/convert_exprs.rs, src/hir/hir_maker.rs, src/hir/hir_maker_context.rs, src/hir/mod.rs, src/names.rs, src/ty.rs
Fixed type system so that `ret = Array<T>.new` is possible
fix #205
=> impl. Array#reverse

builtin/array.sk, src/corelib/array.rs, src/corelib/mod.rs, src/hir/class_dict/indexing.rs, src/ty.rs
=> fix: Int does not conform to T

builtin/array.sk, src/hir/class_dict/indexing.rs
=> Array.repeat

builtin/array.sk, src/ast.rs, src/hir/accessors.rs, src/hir/class_dict/mod.rs, src/hir/class_dict/query.rs, src/hir/convert_exprs.rs, src/hir/hir_maker.rs, src/hir/hir_maker_context.rs, src/hir/signature.rs, src/hir/sk_class.rs, src/names.rs, src/parser/definition_parser.rs, src/parser/expression_parser.rs, src/ty.rs, tests/expression_parser_test.rs
=> Generic method (like Array#map<U>)

src/code_gen/mod.rs, src/hir/hir_maker.rs
=> refactor: gen_body_of_new

src/code_gen/gen_exprs.rs, src/corelib/fn_x.rs, src/corelib/object.rs, src/hir/accessors.rs, src/hir/mod.rs, src/parser/lexer.rs
=> Add `@` to internal names of ivars

builtin/array.sk, src/hir/class_dict/query.rs, src/hir/convert_exprs.rs, src/hir/hir_maker.rs, src/hir/signature.rs, src/hir/sk_class.rs, src/ty.rs, tests/sk/array.sk
Also fixed type checking of calling a generic method of Array (`map` this time) from other method of Array (`flat_map` this time)
=> impl. Array#flat_map

builtin/array.sk, src/code_gen/gen_exprs.rs, src/hir/class_dict/query.rs, src/hir/hir_maker.rs, src/hir/signature.rs, src/hir/sk_class.rs, src/ty.rs
=> Array.build

builtin/array.sk, src/hir/class_dict/indexing.rs, src/hir/hir_maker.rs, src/hir/hir_maker_context.rs, src/names.rs
=> Fix typarams of class methods

builtin/array.sk, builtin/int.sk, builtin/string.sk, src/hir/convert_exprs.rs, src/ty.rs
=> Allow calling a lambda without `.call`

README.md
Prerequisites spelling change. 
Extremely small typo
=> Extremely small typo fix

.github/workflows/ubuntu.yml
This PR speed up CI with cache.
=> ci: Use cache

src/ast.rs, src/corelib/fn_x.rs, src/corelib/mod.rs, src/hir/class_dict/indexing.rs, src/hir/class_dict/mod.rs, src/hir/class_dict/query.rs, src/hir/convert_exprs.rs, src/hir/hir_maker.rs, src/hir/mod.rs, src/hir/signature.rs, src/hir/sk_class.rs, src/mir/vtable.rs, src/names.rs, src/parser/definition_parser.rs, src/parser/expression_parser.rs, src/runner.rs, src/ty.rs, src/type_checking/mod.rs, tests/sk/generics.sk
This PR implements inheritance from generic class. eg.
```
class Maybe<V>; end
class Some<V> : Maybe<V>; end
class None : Maybe<Never>; end
```
refs #115
=> Inheritance from generic class

builtin/maybe.sk, src/hir/class_dict/indexing.rs, src/hir/class_dict/mod.rs, src/hir/hir_maker.rs, src/hir/signature.rs, src/names.rs, tests/sk/enum.sk
This PR implements getters of an enum case class.
=> Implementing enum part.3

builtin/void.sk, tests/sk/void.sk
=> feat: implement Void#to_s

builtin/metaclass.sk, doc/spec/src/classes.md, src/code_gen/gen_exprs.rs, src/code_gen/utils.rs, src/code_gen/values.rs, src/corelib/metaclass.rs, src/corelib/mod.rs, src/hir/class_dict/indexing.rs, src/hir/class_dict/query.rs, src/hir/hir_maker.rs, src/names.rs, src/ty.rs
=> feat: Add class Metaclass

src/parser/lexer.rs
There is still a panic in lexer.
=> feat(parser): return error instead of panic in lexer

builtin/array.sk, builtin/hash.sk, builtin/string.sk, src/parser/expression_parser.rs, src/parser/lexer.rs
=> Allow '?' as method name suffix

builtin/dict.sk
because "Hash" is not a name of data structure
=> change: Rename `Hash` to `Dict`

lib/shiika_core/src/names.rs, lib/shiika_core/src/ty.rs, lib/shiika_core/src/ty/lit_ty.rs, lib/shiika_core/src/ty/term_ty.rs, lib/shiika_core/src/ty/typaram.rs, lib/skc_ast2hir/src/class_dict/query.rs, lib/skc_ast2hir/src/convert_exprs.rs, lib/skc_ast2hir/src/hir_maker.rs, lib/skc_ast2hir/src/pattern_match.rs, lib/skc_codegen/src/utils.rs, lib/skc_hir/src/lib.rs, lib/skc_hir/src/sk_class.rs, lib/skc_hir/src/sk_method.rs, lib/skc_hir/src/superclass.rs
This PR merges TyMeta, TySpe, TySpeMeta, etc. into just TyRaw.
=> Refactoring ty.rs (part.1)

lib/shiika_core/src/ty/lit_ty.rs, lib/shiika_core/src/ty/term_ty.rs, lib/skc_ast2hir/src/module_dict.rs, lib/skc_ast2hir/src/module_dict/indexing.rs, lib/skc_ast2hir/src/module_dict/query.rs, lib/skc_ast2hir/src/rustlib_methods.rs, lib/skc_codegen/src/lib.rs, lib/skc_corelib/src/lib.rs, lib/skc_hir/src/class_info.rs, lib/skc_hir/src/lib.rs, lib/skc_hir/src/sk_module.rs, lib/skc_mir/src/vtable.rs
Extract class-specific properties into `ClassInfo` from `SkModule`.
=> Split SkModule and ClassInfo

lib/shiika_ast/src/lib.rs, lib/shiika_ast/src/token.rs, lib/shiika_core/src/ty.rs, lib/shiika_core/src/ty/erasure.rs, lib/shiika_parser/src/definition_parser.rs, lib/shiika_parser/src/lexer.rs, lib/skc_ast2hir/src/hir_maker.rs, lib/skc_ast2hir/src/lib.rs, lib/skc_ast2hir/src/module_dict.rs, lib/skc_ast2hir/src/module_dict/indexing.rs, lib/skc_ast2hir/src/module_dict/query.rs, lib/skc_codegen/src/lib.rs, lib/skc_hir/src/class_info.rs, lib/skc_hir/src/lib.rs, lib/skc_hir/src/signature.rs, lib/skc_hir/src/sk_module.rs
This PR adds new keyword `module` (behaves same as `class` currently)
=> Add syntax to define a module

lib/shiika_ast/src/lib.rs, lib/shiika_ast/src/token.rs, lib/shiika_core/src/names.rs, lib/shiika_core/src/names/class_name.rs, lib/shiika_core/src/names/const_name.rs, lib/shiika_core/src/names/type_name.rs, lib/shiika_core/src/ty/lit_ty.rs, lib/shiika_core/src/ty/term_ty.rs, lib/shiika_core/src/ty/typaram_ref.rs, lib/shiika_parser/src/definition_parser.rs, lib/skc_ast2hir/src/class_dict/indexing.rs, lib/skc_ast2hir/src/class_dict/query.rs, lib/skc_ast2hir/src/rustlib_methods.rs, lib/skc_codegen/src/code_gen_context.rs, lib/skc_codegen/src/utils.rs, lib/skc_corelib/src/lib.rs, lib/skc_hir/src/sk_type/sk_class.rs
cleanup (and some refactorings)
=> Delete unused code

lib/shiika_core/src/names/class_name.rs, lib/shiika_core/src/names/module_name.rs, lib/shiika_core/src/names/namespace.rs, lib/shiika_core/src/ty/erasure.rs, lib/skc_ast2hir/src/class_dict.rs, lib/skc_ast2hir/src/class_dict/build_wtable.rs, lib/skc_ast2hir/src/class_dict/class_index.rs, lib/skc_ast2hir/src/class_dict/indexing.rs, lib/skc_ast2hir/src/class_dict/query.rs, lib/skc_ast2hir/src/convert_exprs.rs, lib/skc_ast2hir/src/hir_maker.rs, lib/skc_codegen/src/gen_exprs.rs, lib/skc_codegen/src/lambda.rs, lib/skc_codegen/src/lib.rs, lib/skc_codegen/src/utils.rs, lib/skc_codegen/src/values.rs, lib/skc_codegen/src/wtable.rs, lib/skc_corelib/src/class.rs, lib/skc_hir/src/lib.rs, lib/skc_hir/src/sk_type.rs, lib/skc_hir/src/sk_type/sk_class.rs, lib/skc_hir/src/sk_type/sk_module.rs, lib/skc_hir/src/sk_type/wtable.rs, lib/skc_hir/src/superclass.rs, lib/skc_rustlib/src/builtin.rs, lib/skc_rustlib/src/builtin/class.rs, lib/skc_rustlib/src/builtin/class/witness_table.rs
This PR adds HirModuleMethodCall. The codegen part is not finished though.
=> Add HirModuleMethodCall

Cargo.toml, lib/shiika_ffi/src/lib.rs, lib/shiika_parser/src/definition_parser.rs, lib/skc_ast2hir/src/class_dict.rs, lib/skc_ast2hir/src/class_dict/query.rs, lib/skc_codegen/src/gen_exprs.rs, lib/skc_hir/src/lib.rs, lib/skc_hir/src/sk_type.rs
This PR updates Rust edition to 2021 and fixes newer clippy warnings.
=> Update to Edition2021

builtin/array.sk, builtin/string.sk, lib/shiika_parser/src/expression_parser.rs
This PR removes conditional operator.
Use `if-then-else-end` instead
=> Remove conditional operator (? :)

lib/skc_ast2hir/src/hir_maker_context.rs, lib/skc_ast2hir/src/pattern_match.rs, lib/skc_codegen/src/code_gen_context.rs, lib/skc_codegen/src/gen_exprs.rs, lib/skc_codegen/src/lib.rs, lib/skc_hir/src/pattern_match.rs, tests/sk/match_expression.sk
=> MatchClause should have its own lvar scope

Cargo.lock, Cargo.toml, Rakefile, lib/shiika_ast/src/lib.rs, lib/shiika_ast/src/location.rs, lib/shiika_parser/src/ast_builder.rs, lib/shiika_parser/src/expression_parser.rs, lib/shiika_parser/src/lexer.rs, lib/shiika_parser/src/lib.rs, lib/shiika_parser/src/source_file.rs, lib/skc_ast2hir/Cargo.toml, lib/skc_ast2hir/src/convert_exprs.rs, lib/skc_ast2hir/src/convert_exprs/method_call.rs, lib/skc_ast2hir/src/hir_maker.rs, lib/skc_ast2hir/src/lib.rs, lib/skc_ast2hir/src/pattern_match.rs, lib/skc_ast2hir/src/type_system/type_checking.rs, lib/skc_corelib/src/lib.rs, lib/skc_hir/src/lib.rs, src/runner.rs
=> Add location to ast and hir (part.1)

.github/workflows/ubuntu.yml, README.md, lib/shiika_parser/src/error.rs, lib/shiika_parser/src/lexer.rs, lib/shiika_parser/src/lib.rs, lib/skc_ast2hir/src/error.rs, lib/skc_ast2hir/src/lib.rs
=> No nightly

Cargo.lock, lib/skc_rustlib/Cargo.toml, lib/skc_rustlib/provided_methods.json5, lib/skc_rustlib/src/builtin/array.rs, lib/skc_rustlib/src/builtin/string.rs
This PR implements String#chars, which slices a string into array of character (more specifically, grapheme clusters.)
=> impl. String#chars

lib/skc_rustlib/provided_methods.json5, lib/skc_rustlib/src/builtin.rs, lib/skc_rustlib/src/builtin/fn_x.rs, lib/skc_rustlib/src/builtin/shiika_internal_ptr.rs, lib/skc_rustlib/src/builtin/shiika_internal_ptr_typed.rs, lib/skc_rustlib/src/builtin/string.rs, lib/skc_rustlib/src/builtin/void.rs
However it is not enabled yet because it does not support `break` yet.
=> impl. String#each_char in Rust

lib/skc_ast2hir/src/convert_exprs.rs, lib/skc_ast2hir/src/ctx_stack.rs, lib/skc_ast2hir/src/pattern_match.rs, lib/skc_codegen/src/gen_exprs.rs, tests/sk/loops_and_jumps.sk
=> Break in match

lib/skc_ast2hir/src/hir_maker.rs, tests/sk/enum.sk
With this PR enums can have class methods or inner classes.
=> impl. definitions in enum

lib/shiika_ast/src/lib.rs, lib/shiika_parser/src/expression_parser.rs, lib/skc_ast2hir/src/convert_exprs.rs, lib/skc_ast2hir/src/pattern_match.rs
=> Allow bool/float/string literal in a pattern

lib/shiika_core/src/names/method_name.rs, lib/shiika_core/src/ty/lit_ty.rs, lib/shiika_core/src/ty/term_ty.rs, lib/shiika_core/src/ty/typaram_ref.rs, lib/skc_ast2hir/src/ctx_stack.rs, lib/skc_hir/src/signature.rs
=> fix type of self in a class method

lib/shiika_parser/src/ast_builder.rs, lib/shiika_parser/src/expression_parser.rs, lib/skc_ast2hir/src/convert_exprs.rs, lib/skc_ast2hir/src/convert_exprs/block.rs, lib/skc_ast2hir/src/type_system/type_checking.rs, lib/skc_hir/src/lib.rs
This PR improves error message of block arity error.
=> Add error report for block arity error

lib/shiika_ast/src/lib.rs, lib/shiika_core/src/names.rs, lib/shiika_core/src/names/type_name.rs, lib/shiika_parser/src/ast_builder.rs, lib/shiika_parser/src/definition_parser.rs, lib/skc_ast2hir/Cargo.toml, lib/skc_ast2hir/src/class_dict/indexing.rs, lib/skc_ast2hir/src/convert_exprs/params.rs, lib/skc_ast2hir/src/rustlib_methods.rs, lib/skc_ast2hir/src/type_system/type_checking.rs, lib/skc_corelib/src/lib.rs, lib/skc_error/Cargo.toml, lib/skc_error/README.md, lib/skc_error/src/lib.rs
This PR improves the message for "unknown type" error.
=> Definition parser error location

lib/skc_ast2hir/src/class_dict/indexing.rs
=> fix: passing wrong namespace

lib/skc_ast2hir/src/class_dict/indexing.rs
=> fix: index accessors

lib/shiika_core/src/ty/term_ty.rs, tests/sk/generics.sk
This PR fixes compile error #422.
=> fix compile error on passing a type parameter for method tyarg

lib/skc_ast2hir/src/class_dict/build_wtable.rs, lib/skc_ast2hir/src/class_dict/query.rs, lib/skc_ast2hir/src/convert_exprs/block.rs, lib/skc_ast2hir/src/convert_exprs/method_call.rs, lib/skc_ast2hir/src/type_inference/method_call_inf.rs, lib/skc_ast2hir/src/type_system/type_checking.rs, lib/skc_hir/src/sk_type/sk_class.rs, lib/skc_hir/src/superclass.rs, tests/sk/block.sk
=> Fix compile error on block type inference

lib/skc_codegen/src/lib.rs
=> Remove `putd_tmpl` and `putf_tmpl`

lib/shiika_parser/src/lexer.rs
=> Set state to `LexerState::ExprBegin` after comment

lib/shiika_parser/src/expression_parser.rs, tests/sk/array.sk
=> Allow space in square brackets

lib/skc_ast2hir/src/convert_exprs.rs, lib/skc_ast2hir/src/ctx_stack.rs, lib/skc_ast2hir/src/hir_maker.rs, lib/skc_ast2hir/src/hir_maker_context.rs, lib/skc_ast2hir/src/pattern_match.rs, lib/skc_codegen/src/lambda.rs, lib/skc_codegen/src/lib.rs, lib/skc_codegen/src/utils.rs, lib/skc_hir/src/lib.rs
=> fix: Allocate captured lvars on heap

lib/shiika_parser/src/definition_parser.rs, lib/shiika_parser/src/lexer.rs
=> Allow setters to accepts only 1 argument

lib/skc_ast2hir/src/class_dict/query.rs
=> Check number of type arguments

lib/skc_ast2hir/src/convert_exprs/method_call.rs, lib/skc_ast2hir/src/hir_maker.rs, lib/skc_ast2hir/src/type_inference/method_call_inf.rs, lib/skc_ast2hir/src/type_system/type_checking.rs, lib/skc_hir/src/lib.rs, tests/sk/block.sk
=> fix wrong type error

builtin/object.sk, lib/skc_rustlib/provided_methods.json5, lib/skc_rustlib/src/builtin/object.rs
This PR adds Object#gets which reads one line from stdin.
=> impl. Object#gets

README.md, doc/guide/src/SUMMARY.md, doc/guide/src/install.md, lib/skc_codegen/src/lib.rs, src/runner.rs
This PR introduces `SHIIKA_ROOT` environment variable. `shiika` will look for `builtin/index.sk`, etc. from that directory (if defined).
fix #459
=> Check SHIIKA_ROOT if defined

src/runner.rs
This PR fixes some errors I got on Windows.
=> fix: "target" should be relative to SHIIKA_ROOT 

lib/shiika_ast/src/lib.rs, lib/shiika_parser/src/definition_parser.rs, lib/skc_ast2hir/src/accessors.rs, lib/skc_ast2hir/src/class_dict/indexing.rs, lib/skc_ast2hir/src/convert_exprs.rs, lib/skc_ast2hir/src/convert_exprs/block.rs, lib/skc_ast2hir/src/convert_exprs/lvar.rs, lib/skc_ast2hir/src/convert_exprs/method_call.rs, lib/skc_ast2hir/src/convert_exprs/params.rs, lib/skc_ast2hir/src/hir_maker.rs, lib/skc_ast2hir/src/hir_maker_context.rs, lib/skc_ast2hir/src/rustlib_methods.rs, lib/skc_codegen/src/gen_exprs.rs, lib/skc_codegen/src/lambda.rs, lib/skc_hir/src/lib.rs, lib/skc_hir/src/signature.rs, lib/skc_hir/src/sk_method.rs, tests/sk/method_call.sk
This PR implements "default argment" like:
```sk
class A
def foo(a: Int = 0)
...
```
=> impl. Default arg

.github/workflows/ci.yml, examples/fib.sk, examples/lifegame.sk, examples/mandel.sk, examples/ray.sk, release_test.sh
This PR fixes broken examples and make CI to test them.
=> ci: Run examples/*.sk

Cargo.lock, Cargo.toml, lib/skc_language_server/Cargo.toml, lib/skc_language_server/README.md, lib/skc_language_server/package-lock.json, lib/skc_language_server/src/backend.rs, lib/skc_language_server/src/main.rs, lib/skc_language_server/src/server.rs
This PR adds lib/skc_language_server. (Just a prototype; no actual feature now.)
=> Language server prototype

lib/skc_ast2hir/src/convert_exprs.rs, lib/skc_ast2hir/src/type_system/type_checking.rs
This PR adds error report to `return` type error.
=> Add error report to `return` type error

lib/shiika_core/src/names/class_name.rs, lib/shiika_core/src/names/module_name.rs, lib/skc_ast2hir/src/class_dict/indexing.rs, lib/skc_ast2hir/src/hir_maker.rs
This PR removes some methods marked as "TODO: delete this".
=> refactor shiika_core

builtin/object.sk, builtin/shiika_internal.sk, lib/skc_rustlib/provided_methods.json5, lib/skc_rustlib/src/builtin/object.rs, lib/skc_rustlib/src/builtin/shiika_internal_memory.rs
This PR implements `Object#sleep` and `Shiika::Internal::Memory.force_gc`.
=> impl. Object#sleep and force_gc

Cargo.lock, Cargo.toml, src/targets.rs
=> fix: mac-sys-info not loaded on mac

doc/guide/src/install.md
What I did:
Specify in install.md to use the latest version of rust
=> Specify in install.md to use the latest version of rust

lib/shiika_parser/src/lexer.rs
What I did:
Remove trailing spaces in lexer.rs
=> [NITS] remove trailing spaces

.github/workflows/ci.yml
The main change is to use LLVM from homebrew. related to #441.
=> add basic support to run ci on mac

Dockerfile, doc/guide/src/develop-in-docker-container.md, doc/guide/src/install.md, docker-compose.yml, setup.sh
- Add docker dev env
-  [x] below command passes
```
docker compose build --no-cache
docker compose exec dev bash
```
And then run tests in container
```
cargo test
```
=> Develop environment in Docker container

lib/shiika_parser/src/expression_parser.rs
Refactor
- Reduced nesting depth
- The code was introduced by #542 
Passes all tests
=> Refactor: implementation for starts with dot

tests/sk/new_line_starts_with_dot.sk
issue: #387
Add test  case 4
```
p [1,2,3]
.select{|i: Int| i % 2 == 0}
.map<Int>{|i: Int| i * 2}
```
=> Add test case 4

lib/skc_async_experiment/src/codegen.rs, lib/skc_async_experiment/src/hir/expr.rs, lib/skc_async_experiment/src/hir/rewriter.rs, lib/skc_async_experiment/src/hir/typing.rs, lib/skc_async_experiment/src/hir/untyped.rs, lib/skc_async_experiment/src/hir/verifier.rs, lib/skc_async_experiment/src/hir/visitor.rs, lib/skc_async_experiment/src/hir_lowering/async_splitter.rs, lib/skc_async_experiment/src/prelude.rs
=> Add name to Expr::ArgRef

lib/shiika_parser/src/expression_parser.rs, tests/sk/parse_unary_plus.sk
Make parser can handle unary plus
You've left comment `TODO: Parse ~, +` above parse_unary_expr
```
let a = +12
let b = +a
puts "ok" if a == b
```
=> Parse unary plus

lib/shiika_core/src/names/const_name.rs, lib/skc_async_experiment/src/codegen.rs, lib/skc_async_experiment/src/codegen/mir_analysis.rs, lib/skc_async_experiment/src/codegen/mir_analysis/list_constants.rs, lib/skc_async_experiment/src/hir.rs, lib/skc_async_experiment/src/hir/expr.rs, lib/skc_async_experiment/src/hir/typing.rs, lib/skc_async_experiment/src/hir/untyped.rs, lib/skc_async_experiment/src/hir_to_mir.rs, lib/skc_async_experiment/src/mir/expr.rs, lib/skc_async_experiment/src/mir/rewriter.rs, lib/skc_async_experiment/src/mir/verifier.rs, lib/skc_async_experiment/src/mir/visitor.rs, lib/skc_async_experiment/src/mir_lowering/async_splitter.rs
This PR implements constants to the new runtime.
=> new_runtime: impl. constants

Cargo.lock, lib/skc_async_experiment/Cargo.toml, lib/skc_async_experiment/src/build.rs, lib/skc_async_experiment/src/build/compiler.rs, lib/skc_async_experiment/src/build/exe_builder.rs, lib/skc_async_experiment/src/build/lib_builder.rs, lib/skc_async_experiment/src/build/loader.rs, lib/skc_async_experiment/src/cli.rs, lib/skc_async_experiment/src/codegen.rs, lib/skc_async_experiment/src/hir_to_mir.rs, lib/skc_async_experiment/src/mir.rs, lib/skc_async_experiment/src/mir/ty.rs, lib/skc_async_experiment/src/package.rs, lib/skc_async_experiment/src/prelude.rs, lib/skc_hir/src/sk_type.rs, lib/skc_hir/src/sk_type/sk_type_base.rs
This PR implements building and linking package's index.sk (and required files).
=> Build .sk in a package

lib/shiika_ffi/src/core_class.rs, lib/shiika_ffi/src/core_class/string.rs, lib/skc_async_experiment/src/build/compiler.rs, lib/skc_async_experiment/src/codegen.rs, lib/skc_async_experiment/src/codegen/string_literal.rs, lib/skc_async_experiment/src/hir/expr.rs, lib/skc_async_experiment/src/hir/typing.rs, lib/skc_async_experiment/src/hir/untyped.rs, lib/skc_async_experiment/src/hir/visitor.rs, lib/skc_async_experiment/src/hir_to_mir.rs, lib/skc_async_experiment/src/mir/expr.rs, lib/skc_async_experiment/src/mir/rewriter.rs, lib/skc_async_experiment/src/mir/ty.rs, lib/skc_async_experiment/src/mir/verifier.rs, lib/skc_async_experiment/src/mir/visitor.rs, lib/skc_async_experiment/src/mir_lowering/async_splitter.rs, lib/skc_async_experiment/src/mir_lowering/resolve_env_op.rs, lib/skc_async_experiment/src/names.rs, lib/skc_async_experiment/src/prelude.rs, packages/core/ext/exports.json5, packages/core/ext/src/core_class.rs, packages/core/ext/src/core_class/object.rs, packages/core/ext/src/core_class/string.rs, packages/core/index.sk, packages/core/lib/string.sk
This PR implements class String to the new runtime.
=> new_runtime: String

lib/skc_ast2hir/src/accessors.rs, lib/skc_async_experiment/src/codegen.rs, lib/skc_async_experiment/src/codegen/llvm_struct.rs, lib/skc_async_experiment/src/mir.rs, lib/skc_async_experiment/src/mir/expr.rs, lib/skc_async_experiment/src/mir/rewriter.rs, lib/skc_async_experiment/src/mir/verifier.rs, lib/skc_async_experiment/src/mir/visitor.rs, lib/skc_async_experiment/src/mir_lowering/async_splitter.rs, lib/skc_async_experiment/src/mir_lowering/pass_async_env.rs, lib/skc_async_experiment/src/mir_lowering/simplify_return.rs, lib/skc_async_experiment/src/mirgen.rs, lib/skc_async_experiment/src/mirgen/collect_allocs.rs, lib/skc_async_experiment/src/mirgen/constants.rs
This PR implements instance variable access to the new runtime (#587).
=> new_runtime: impl. ivars
